apiVersion: v1
kind: Pod
metadata:
  name: valid-pod
  labels:
    name: valid-pod
spec:
  containers:
  - name: kubernetes-serve-hostname
    image: index.alauda.cn/googlecontainer/serve_hostname
    resources:
      limits:
        cpu: "1"
        memory: 512Mi
